-- CRM database: every migration in order (18 files), generated by
-- scripts/supabase-setup-sql.mjs. Paste it in Supabase › SQL Editor and click Run.
-- Safe to run again: each step checks what already exists.

-- ===== 0001_init.sql =====
-- CRM schema for construction & property services.
-- Run once in Supabase > SQL Editor (or with `supabase db push`).
-- The API seeds fictional demo data on its first request.

-- Keeps updated_at current on every update.
create or replace function set_updated_at() returns trigger
language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end $$;

-- Team ---------------------------------------------------------------------
create table if not exists users (
  id          text primary key default gen_random_uuid()::text,
  name        text not null,
  email       text not null,
  phone       text not null default '',
  job_title   text not null default '',
  trade       text not null default '',
  -- admin sees every schedule; technician and broker see only their own
  role        text not null default 'technician' check (role in ('admin', 'technician', 'broker')),
  active      boolean not null default true,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);
create unique index if not exists users_email_key on users (lower(email));
drop trigger if exists users_updated_at on users;
create trigger users_updated_at before update on users for each row execute function set_updated_at();

-- Clients ------------------------------------------------------------------
create table if not exists clients (
  id            text primary key default gen_random_uuid()::text,
  name          text not null,
  contact_name  text not null default '',
  email         text not null default '',
  phone         text not null default '',
  created_at    timestamptz not null default now()
);

-- Developments > blocks > units ---------------------------------------------
create table if not exists developments (
  id             text primary key default gen_random_uuid()::text,
  name           text not null,
  client_id      text references clients (id) on delete set null,
  kind           text not null default 'residential'
                 check (kind in ('residential', 'commercial', 'mixed_use', 'institutional', 'industrial')),
  status         text not null default 'planning'
                 check (status in ('planning', 'under_construction', 'delivered', 'warranty')),
  address        text not null default '',
  city           text not null default '',
  delivery_date  date,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);
create index if not exists developments_client_idx on developments (client_id);
drop trigger if exists developments_updated_at on developments;
create trigger developments_updated_at before update on developments for each row execute function set_updated_at();

create table if not exists blocks (
  id              text primary key default gen_random_uuid()::text,
  development_id  text not null references developments (id) on delete cascade,
  name            text not null,
  floors          integer not null default 1 check (floors between 1 and 200)
);
create index if not exists blocks_development_idx on blocks (development_id);

create table if not exists units (
  id         text primary key default gen_random_uuid()::text,
  block_id   text not null references blocks (id) on delete cascade,
  number     text not null,
  floor      integer not null default 1,
  kind       text not null default '',
  area_sqft  integer not null default 0 check (area_sqft >= 0),
  status     text not null default 'available' check (status in ('available', 'sold', 'delivered', 'in_warranty')),
  occupant   text not null default '',
  unique (block_id, number)
);
create index if not exists units_block_idx on units (block_id);

-- Calendar -----------------------------------------------------------------
create table if not exists calendar_events (
  id              text primary key,
  title           text not null,
  type            text not null,
  mode            text not null default 'on_site' check (mode in ('on_site', 'remote', 'hybrid')),
  completed       boolean not null default false,
  start_at        timestamptz not null,
  end_at          timestamptz not null check (end_at > start_at),
  project         text not null default '',
  client_id       text not null default '',
  client_name     text not null default '',
  ticket_number   text not null default '',
  owner_id        text not null references users (id) on delete restrict,
  property        text not null default '',
  development_id  text references developments (id) on delete set null,
  block_id        text references blocks (id) on delete set null,
  unit_id         text references units (id) on delete set null,
  location        text not null default '',
  notes           text not null default '',
  billable        boolean not null default false,
  group_activity  boolean not null default false,
  timecard_info   text not null default '',
  tags            text[] not null default '{}',
  hours           jsonb not null default '[]',
  files           jsonb not null default '[]',
  expenses        jsonb not null default '[]',
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);
create index if not exists calendar_events_owner_start_idx on calendar_events (owner_id, start_at);
create index if not exists calendar_events_start_idx on calendar_events (start_at);
create index if not exists calendar_events_development_idx on calendar_events (development_id);
drop trigger if exists calendar_events_updated_at on calendar_events;
create trigger calendar_events_updated_at before update on calendar_events for each row execute function set_updated_at();

-- What's New ---------------------------------------------------------------
create table if not exists releases (
  id              bigint primary key,
  title           text not null,
  description     text not null default '',
  what_changes    text not null default '',
  steps           jsonb not null default '[]',
  training_video  text,
  images          jsonb not null default '[]',
  release_date    text not null default '',  -- dd/mm/yyyy, as the page sends it
  release_time    text not null default '',
  author          text not null default '',
  type            text not null check (type in ('Melhoria', 'Correção')),
  product         text not null default '',
  created_at      timestamptz not null default now()
);

-- Shared settings (calendar colors, card fields, tags, seed flag) ----------
create table if not exists app_settings (
  key         text primary key,
  value       jsonb not null,
  updated_at  timestamptz not null default now()
);

-- Security -----------------------------------------------------------------
-- Only the API (service role key, server side) reads and writes these tables.
-- RLS on with no policies blocks the public anon key completely.
alter table users            enable row level security;
alter table clients          enable row level security;
alter table developments     enable row level security;
alter table blocks           enable row level security;
alter table units            enable row level security;
alter table calendar_events  enable row level security;
alter table releases         enable row level security;
alter table app_settings     enable row level security;

-- ===== 0002_tickets.sql =====
-- Tickets with admin-defined workflows and custom fields.
-- Run after 0001_init.sql, in Supabase > SQL Editor.

-- A workflow keeps its statuses and transitions as JSON: they are edited
-- together in the workflow builder and always read as a whole.
create table if not exists workflows (
  id                 text primary key,
  name               text not null,
  description        text not null default '',
  initial_status_id  text not null,
  statuses           jsonb not null default '[]',   -- [{ id, name, color, category }]
  transitions        jsonb not null default '[]',   -- [{ id, from, to, label, roles, requireComment, requiredFields }]
  updated_at         timestamptz not null default now()
);

create table if not exists ticket_types (
  id                text primary key,
  name              text not null,
  description       text not null default '',
  color             text not null default '#2B6CB0',
  workflow_id       text not null references workflows (id) on delete restrict,
  default_priority  text not null default 'medium' check (default_priority in ('low', 'medium', 'high', 'urgent')),
  sla_hours         integer check (sla_hours is null or sla_hours > 0),
  active            boolean not null default true,
  fields            jsonb not null default '[]'     -- [{ id, label, kind, options, required, helpText }]
);

create table if not exists tickets (
  id               text primary key,
  number           integer not null unique,
  title            text not null,
  description      text not null default '',
  type_id          text not null references ticket_types (id) on delete restrict,
  status_id        text not null,
  priority         text not null default 'medium' check (priority in ('low', 'medium', 'high', 'urgent')),
  assignee_id      text references users (id) on delete set null,
  reporter_id      text not null references users (id) on delete restrict,
  requester_name   text not null default '',
  requester_email  text not null default '',
  requester_phone  text not null default '',
  client_id        text not null default '',
  client_name      text not null default '',
  development_id   text references developments (id) on delete set null,
  block_id         text references blocks (id) on delete set null,
  unit_id          text references units (id) on delete set null,
  property         text not null default '',
  location         text not null default '',
  due_at           timestamptz,
  fields           jsonb not null default '{}',     -- custom field values by field id
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),
  closed_at        timestamptz
);
create index if not exists tickets_assignee_idx on tickets (assignee_id);
create index if not exists tickets_type_status_idx on tickets (type_id, status_id);

-- Every creation, status change, comment and reassignment.
create table if not exists ticket_activity (
  id                text primary key,
  ticket_id         text not null references tickets (id) on delete cascade,
  at                timestamptz not null default now(),
  user_id           text not null references users (id) on delete restrict,
  kind              text not null check (kind in ('created', 'status', 'comment', 'assigned', 'edited', 'fields')),
  from_status_id    text,
  to_status_id      text,
  transition_label  text,
  comment           text,
  assignee_id       text
);
create index if not exists ticket_activity_ticket_idx on ticket_activity (ticket_id, at);

-- Only the API (service role) reads and writes these tables.
alter table workflows        enable row level security;
alter table ticket_types     enable row level security;
alter table tickets          enable row level security;
alter table ticket_activity  enable row level security;

-- ===== 0003_field_service.sql =====
-- Field service reports (check-in, checklist, parts, photos, signature),
-- stored with the appointment. Run after 0002_tickets.sql.
alter table calendar_events add column if not exists service jsonb;

-- ===== 0004_ticket_attachments.sql =====
-- Handle ticket screen: files attached to a ticket, and "attachment" entries
-- in its history. Run after 0003_field_service.sql.
-- Custom field show conditions (FieldDef.showWhen) live in ticket_types.fields
-- (jsonb) and need no schema change.

alter table tickets add column if not exists attachments jsonb not null default '[]';
-- [{ id, name, type, size, dataUrl, uploadedBy, uploadedAt }]

alter table ticket_activity drop constraint if exists ticket_activity_kind_check;
alter table ticket_activity add constraint ticket_activity_kind_check
  check (kind in ('created', 'status', 'comment', 'assigned', 'edited', 'fields', 'attachment'));

-- ===== 0005_sub_tickets.sql =====
-- Sub-tickets: follow-ups split from a ticket, e.g. a task action a
-- technician left for later. Run after 0004_ticket_attachments.sql.
alter table tickets add column if not exists parent_id text references tickets (id) on delete set null;
alter table tickets add column if not exists origin jsonb;  -- { eventId, actionId, actionLabel }
create index if not exists tickets_parent_idx on tickets (parent_id);

-- ===== 0006_drop_timecard_info.sql =====
-- "Timecard info" was removed from appointments (field, badge and card tag).
alter table calendar_events drop column if exists timecard_info;

-- ===== 0007_contacts.sql =====
-- Contacts: lead portfolios. Each lead is owned by one team member (its
-- portfolio); interactions (calls, emails, transfers...) are kept as JSON.
create table if not exists contacts (
  id              text primary key,
  name            text not null,
  email           text not null default '',
  phone           text not null default '',
  company         text not null default '',
  owner_id        text references users(id) on delete set null,
  stage_id        text not null,
  temperature     text not null default 'warm' check (temperature in ('hot', 'warm', 'cold')),
  source          text not null default '',
  development_id  text references developments(id) on delete set null,
  budget          numeric,
  notes           text not null default '',
  next_follow_up  date,
  last_contact_at timestamptz,
  interactions    jsonb not null default '[]'::jsonb,
  created_by      text not null,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

create index if not exists contacts_owner_idx on contacts (owner_id);
create index if not exists contacts_email_idx on contacts (lower(email));

alter table contacts enable row level security;

-- ===== 0008_dashboards.sql =====
-- Custom dashboards: a named grid of widgets (stored as JSON), owned by one
-- person and optionally shared with the team.
create table if not exists dashboards (
  id          text primary key,
  name        text not null,
  description text not null default '',
  owner_id    text not null references users(id) on delete cascade,
  shared      boolean not null default false,
  range       text not null default '90d',
  widgets     jsonb not null default '[]'::jsonb,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create index if not exists dashboards_owner_idx on dashboards (owner_id);

alter table dashboards enable row level security;

-- ===== 0009_reports.sql =====
-- Saved reports: the source, columns, filters, period, grouping and sorting
-- someone chose (as JSON), owned by one person and optionally shared.
create table if not exists reports (
  id          text primary key,
  name        text not null,
  description text not null default '',
  owner_id    text not null references users(id) on delete cascade,
  shared      boolean not null default false,
  source      text not null check (source in ('tickets', 'appointments', 'contacts')),
  columns     jsonb not null default '[]'::jsonb,
  date_field  text not null default 'created',
  period      jsonb not null default '{"kind":"30d"}'::jsonb,
  filters     jsonb not null default '{"state":"all"}'::jsonb,
  group_by    text,
  sort        jsonb not null default '{"column":"","dir":"desc"}'::jsonb,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create index if not exists reports_owner_idx on reports (owner_id);

alter table reports enable row level security;

-- ===== 0010_engineering.sql =====
-- Engineering: a role that answers the field's technical questions, and the
-- question itself, kept on the sub-ticket it is about.
alter table users drop constraint if exists users_role_check;
alter table users add constraint users_role_check check (role in ('admin', 'technician', 'broker', 'engineer'));

alter table tickets add column if not exists engineering jsonb;
create index if not exists tickets_engineering_open_idx on tickets ((engineering->>'status')) where engineering is not null;

-- ===== 0011_billing.sql =====
-- Billing: one payment plan per deal (a sales ticket). Installments, their
-- payments, promises, renegotiations and cadence steps are kept as JSON.
create table if not exists billing (
  id             text primary key,
  ticket_id      text not null unique references tickets(id) on delete cascade,
  ticket_number  integer not null,
  customer       jsonb not null default '{}'::jsonb,
  property       text not null default '',
  total_price    numeric not null,
  installments   jsonb not null default '[]'::jsonb,
  created_by     text not null,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);

alter table billing enable row level security;

-- ===== 0012_dashboard_sharing.sql =====
-- Dashboards shared with chosen accesses (roles) and people, besides "everyone".
alter table dashboards add column if not exists share_with jsonb not null default '{"roles": [], "users": []}'::jsonb;

-- ===== 0013_development_details.sql =====
-- Developments: stage and progress of the works, photos (links with a kind:
-- photo, render, floor plan, construction) and apartment types. Units: their
-- type, bedrooms, bathrooms and garage spots.
alter table developments add column if not exists stage text;
alter table developments add column if not exists progress integer;
alter table developments add column if not exists photos jsonb not null default '[]'::jsonb;
alter table developments add column if not exists unit_types jsonb not null default '[]'::jsonb;
alter table units add column if not exists type_id text;
alter table units add column if not exists bedrooms integer not null default 0;
alter table units add column if not exists bathrooms integer not null default 0;
alter table units add column if not exists parking integer not null default 0;
alter table blocks add column if not exists photos jsonb not null default '[]'::jsonb;

-- ===== 0014_access_profiles.sql =====
-- Custom access profiles (stored in settings as "menuAccess"): a person may use
-- one; their role is the one the profile works like.
alter table users add column if not exists access_id text;

-- ===== 0015_release_new_feature.sql =====
-- What's New: a third kind of note, "Novidade" (new feature).
alter table releases drop constraint if exists releases_type_check;
alter table releases add constraint releases_type_check check (type in ('Novidade', 'Melhoria', 'Correção'));

-- ===== 0016_status_emails.sql =====
-- Emails sent when a ticket reaches a status (Settings › Workflows): they go
-- on the ticket's history, with who got them and what they said.
alter table ticket_activity drop constraint if exists ticket_activity_kind_check;
alter table ticket_activity add constraint ticket_activity_kind_check
  check (kind in ('created', 'status', 'comment', 'assigned', 'edited', 'fields', 'attachment', 'email'));
alter table ticket_activity add column if not exists email jsonb;

-- ===== 0017_billing_sold_unit.sql =====
-- What each payment plan sold (development, block and unit) and when it was bought.
alter table billing add column if not exists sold jsonb;
alter table billing add column if not exists purchased_on date;

-- ===== 0018_back_office_role.sql =====
-- Access profiles: the "Back office" way of working (HR, finance, admin staff)
-- is stored as the role "staff".
alter table users drop constraint if exists users_role_check;
alter table users add constraint users_role_check check (role in ('admin', 'technician', 'broker', 'engineer', 'staff'));
