import type { ReleaseRecord } from "../../shared/releases.js";

/**
 * Fictional release notes for the What's New page (portfolio demo): the
 * standout features, each with a short screen clip from `public/changelog/`.
 * `data` uses dd/mm/yyyy; `tipo` is "Novidade" (new feature), "Melhoria"
 * (improvement) or "Correção" (fix).
 */
export const SEED_RELEASES: ReleaseRecord[] = [
	{
		id: 11,
		titulo: "Collection messages that send themselves",
		descricao: "Set up the reminders around each installment's due date (so many days before, on the day or after) and the CRM sends the email, SMS or WhatsApp on its own, on the right day.",
		oQueMuda: "Deals has a Message automation tab: turn a step Automatic, write the message with {name}, {amount}, {due}… and see what goes out in the next 14 days. Every contact lands on the new Collections timeline, with the message as it was sent. And a ticket's status can now email the customer or the team when a ticket gets there.",
		passoAPasso: [
			"Open Deals › Message automation.",
			"Add or edit a step: how many days before or after the due date, the channel and the message.",
			"Switch Automatic on (email, SMS, WhatsApp); calls and letters stay on Today's actions.",
			"Check Scheduled · next 14 days, and save.",
			"Follow every contact on Deals › Collections timeline, filtered by channel, period or deal.",
			"For status emails: Settings › Workflows › a status › Email when a ticket gets here.",
		],
		imagens: ["/changelog/message-automation.gif", "/changelog/collections-timeline.gif", "/changelog/status-email.gif"],
		data: "26/09/2026",
		hora: "17:00",
		usuario: "Emily Carter",
		tipo: "Novidade",
		produto: "Deals",
	},
	{
		id: 10,
		titulo: "Workflows you configure",
		descricao: "Each ticket type follows a workflow: the statuses a ticket goes through and the paths between them. Create your own and adjust them whenever the process changes.",
		oQueMuda: "The preview draws every path as you edit: solid arrows move forward, dashed ones go back, and steps like Cancel stay available from any status. Mark which statuses need a visit on the calendar or wait on engineering, and tickets can only move along the steps you allow.",
		passoAPasso: [
			"Go to Settings › Workflows.",
			"Pick a workflow, or click New workflow.",
			"Add the statuses: name, category, color and which one starts.",
			"Check the preview, then Save.",
			"In Ticket types & fields, choose which workflow each type follows.",
		],
		imagens: ["/changelog/workflows.gif"],
		data: "26/09/2026",
		hora: "15:30",
		usuario: "Emily Carter",
		tipo: "Novidade",
		produto: "Tickets",
	},
	{
		id: 9,
		titulo: "Every request on one board",
		descricao: "Warranty claims, maintenance and sales inquiries live as tickets that move through their own statuses, on a board or in a list.",
		oQueMuda: "Pick a type to see only its statuses, switch to the list to sort and search, and spot what's overdue at a glance.",
		passoAPasso: [
			"Open Tickets from the side menu.",
			"Click a type (Warranty claim, Maintenance request…) to focus on it.",
			"Switch between Board and List at the top; drag a card to move it on.",
		],
		imagens: ["/changelog/tickets.gif"],
		data: "26/09/2026",
		hora: "09:00",
		usuario: "Emily Carter",
		tipo: "Novidade",
		produto: "Tickets",
	},
	{
		id: 8,
		titulo: "Access profiles you design",
		descricao: "Create as many accesses as you need (HR, finance, site supervisor) and decide how each one works in the CRM.",
		oQueMuda: "Each access has its way of working (field, engineering, sales or back office), its screens, its actions and its home page. Give it to a person in Team.",
		passoAPasso: [
			"Go to Settings › Menu by access and click New access.",
			"Name it and pick how they work, e.g. HR → Back office.",
			"Switch on the screens and actions it needs, then save.",
			"In Team, open the person and choose the new access.",
		],
		imagens: ["/changelog/access-profiles.gif"],
		data: "24/09/2026",
		hora: "16:20",
		usuario: "Emily Carter",
		tipo: "Novidade",
		produto: "Settings",
	},
	{
		id: 7,
		titulo: "Apartment types with photos and floor plans",
		descricao: "Each development lists its apartment types, with area, bedrooms, bathrooms and garage spots, and a gallery of photos, renders and the floor plan.",
		oQueMuda: "Brokers show a unit in seconds: open the type, swipe through the pictures and jump to the next type without closing it.",
		passoAPasso: [
			"Open Developments and pick a development.",
			"Click an apartment type to open its gallery.",
			"Use the arrows to see the pictures, and the strip below to change type.",
		],
		imagens: ["/changelog/apartment-types.gif"],
		data: "22/09/2026",
		hora: "11:45",
		usuario: "Sophia Martinez",
		tipo: "Novidade",
		produto: "Developments",
	},
	{
		id: 6,
		titulo: "The visit report, on site",
		descricao: "Technicians check in, work through the actions to do, send questions to engineering and collect the signature, all from their phone.",
		oQueMuda: "The office sees the visit move in real time, and every action done on site closes its own sub-ticket.",
		passoAPasso: [
			"Open Tasks and pick today's visit.",
			"Check in when you arrive; go through Actions to do.",
			"Validate with the customer and collect the signature to finish.",
		],
		imagens: ["/changelog/technician-visit.gif"],
		data: "18/09/2026",
		hora: "08:30",
		usuario: "Jack Thompson",
		tipo: "Novidade",
		produto: "Tasks",
	},
	{
		id: 5,
		titulo: "A month view you can read",
		descricao: "The month calendar now shows each appointment as one line (start time and title), in the color of its type.",
		oQueMuda: "Busy days stay tidy: hover a line to see the whole title and place, click it for the details, or open the day or the week.",
		passoAPasso: [
			"Open Calendar and choose Month.",
			"Hover an appointment for its details, click it to open.",
			"Use Day and Week for the full cards.",
		],
		imagens: ["/changelog/calendar.gif"],
		data: "15/09/2026",
		hora: "14:10",
		usuario: "Emily Carter",
		tipo: "Melhoria",
		produto: "Calendar",
	},
	{
		id: 4,
		titulo: "Settings, one topic at a time",
		descricao: "Settings opens on an overview of what you can shape, and each topic gets the full width of the screen.",
		oQueMuda: "Workflows, ticket types, the calendar, lead stages, billing and access are grouped and summarized, so you see what's set up before you open it.",
		passoAPasso: ["Open Settings.", "Pick a topic.", "Use Back to settings, at the top left, to return."],
		imagens: ["/changelog/settings.gif"],
		data: "10/09/2026",
		hora: "10:00",
		usuario: "Emily Carter",
		tipo: "Melhoria",
		produto: "Settings",
	},
	{
		id: 3,
		titulo: "Lighter fields, one corner size",
		descricao: "Inputs and lists now stand out from the page, and cards, buttons and fields share the same rounded corners.",
		oQueMuda: "Forms are easier to scan: every place you can type is white, on the soft blue-gray page.",
		passoAPasso: [],
		imagens: [],
		data: "02/09/2026",
		hora: "17:30",
		usuario: "Sophia Martinez",
		tipo: "Melhoria",
		produto: "Design",
	},
	{
		id: 2,
		titulo: "Sub-tickets show up for the office",
		descricao: "A sub-ticket a technician opens during a visit now appears right away for administrators and engineering.",
		oQueMuda: "The ticket page refreshes on its own, so nobody misses work found on site.",
		passoAPasso: [],
		imagens: [],
		data: "20/08/2026",
		hora: "12:15",
		usuario: "Emily Carter",
		tipo: "Correção",
		produto: "Tickets",
	},
	{
		id: 1,
		titulo: "Calendar settings only for who can change them",
		descricao: "The calendar settings button is hidden for people who can't edit the calendar.",
		oQueMuda: "Technicians and brokers get a cleaner toolbar, with Yesterday and Today next to the views.",
		passoAPasso: [],
		imagens: [],
		data: "30/07/2026",
		hora: "09:40",
		usuario: "Emily Carter",
		tipo: "Correção",
		produto: "Calendar",
	},
];

/** Titles of the first demo notes, replaced by the ones above in seed v22. */
export const OLD_SEED_RELEASE_TITLES = [
	"Role-based calendars",
	"Developments, blocks and units",
	"Team directory",
	"Customizable appointment cards",
	"Appointments saved on the wrong day",
	"Log hours, files and expenses from the appointment",
	"Read more button disappeared on cards",
	"Welcome to the new CRM",
];
