/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CalendarIndexRouteImport } from './routes/calendar/index'
import { Route as ContactsIndexRouteImport } from './routes/contacts/index'
import { Route as DashboardsIndexRouteImport } from './routes/dashboards/index'
import { Route as DealsIndexRouteImport } from './routes/deals/index'
import { Route as DevelopmentsIndexRouteImport } from './routes/developments/index'
import { Route as ReportsIndexRouteImport } from './routes/reports/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as TeamIndexRouteImport } from './routes/team/index'
import { Route as TechnicianIndexRouteImport } from './routes/technician/index'
import { Route as TechnicianActivityIdRouteImport } from './routes/technician/$activityId'
import { Route as TicketsIndexRouteImport } from './routes/tickets/index'
import { Route as TicketsTicketNumberRouteImport } from './routes/tickets/$ticketNumber'
import { Route as TicketsSettingsRouteImport } from './routes/tickets/settings'
import { Route as WhatsNewIndexRouteImport } from './routes/whats-new/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarIndexRoute = CalendarIndexRouteImport.update({
  id: '/calendar/',
  path: '/calendar/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsIndexRoute = ContactsIndexRouteImport.update({
  id: '/contacts/',
  path: '/contacts/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardsIndexRoute = DashboardsIndexRouteImport.update({
  id: '/dashboards/',
  path: '/dashboards/',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsIndexRoute = DealsIndexRouteImport.update({
  id: '/deals/',
  path: '/deals/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopmentsIndexRoute = DevelopmentsIndexRouteImport.update({
  id: '/developments/',
  path: '/developments/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamIndexRoute = TeamIndexRouteImport.update({
  id: '/team/',
  path: '/team/',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnicianIndexRoute = TechnicianIndexRouteImport.update({
  id: '/technician/',
  path: '/technician/',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnicianActivityIdRoute = TechnicianActivityIdRouteImport.update({
  id: '/technician/$activityId',
  path: '/technician/$activityId',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsIndexRoute = TicketsIndexRouteImport.update({
  id: '/tickets/',
  path: '/tickets/',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsTicketNumberRoute = TicketsTicketNumberRouteImport.update({
  id: '/tickets/$ticketNumber',
  path: '/tickets/$ticketNumber',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsSettingsRoute = TicketsSettingsRouteImport.update({
  id: '/tickets/settings',
  path: '/tickets/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatsNewIndexRoute = WhatsNewIndexRouteImport.update({
  id: '/whats-new/',
  path: '/whats-new/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/technician/$activityId': typeof TechnicianActivityIdRoute
  '/tickets/$ticketNumber': typeof TicketsTicketNumberRoute
  '/tickets/settings': typeof TicketsSettingsRoute
  '/calendar/': typeof CalendarIndexRoute
  '/contacts/': typeof ContactsIndexRoute
  '/dashboards/': typeof DashboardsIndexRoute
  '/deals/': typeof DealsIndexRoute
  '/developments/': typeof DevelopmentsIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/team/': typeof TeamIndexRoute
  '/technician/': typeof TechnicianIndexRoute
  '/tickets/': typeof TicketsIndexRoute
  '/whats-new/': typeof WhatsNewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/technician/$activityId': typeof TechnicianActivityIdRoute
  '/tickets/$ticketNumber': typeof TicketsTicketNumberRoute
  '/tickets/settings': typeof TicketsSettingsRoute
  '/calendar': typeof CalendarIndexRoute
  '/contacts': typeof ContactsIndexRoute
  '/dashboards': typeof DashboardsIndexRoute
  '/deals': typeof DealsIndexRoute
  '/developments': typeof DevelopmentsIndexRoute
  '/reports': typeof ReportsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/team': typeof TeamIndexRoute
  '/technician': typeof TechnicianIndexRoute
  '/tickets': typeof TicketsIndexRoute
  '/whats-new': typeof WhatsNewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/technician/$activityId': typeof TechnicianActivityIdRoute
  '/tickets/$ticketNumber': typeof TicketsTicketNumberRoute
  '/tickets/settings': typeof TicketsSettingsRoute
  '/calendar/': typeof CalendarIndexRoute
  '/contacts/': typeof ContactsIndexRoute
  '/dashboards/': typeof DashboardsIndexRoute
  '/deals/': typeof DealsIndexRoute
  '/developments/': typeof DevelopmentsIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/team/': typeof TeamIndexRoute
  '/technician/': typeof TechnicianIndexRoute
  '/tickets/': typeof TicketsIndexRoute
  '/whats-new/': typeof WhatsNewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/technician/$activityId'
    | '/tickets/$ticketNumber'
    | '/tickets/settings'
    | '/calendar/'
    | '/contacts/'
    | '/dashboards/'
    | '/deals/'
    | '/developments/'
    | '/reports/'
    | '/settings/'
    | '/team/'
    | '/technician/'
    | '/tickets/'
    | '/whats-new/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/technician/$activityId'
    | '/tickets/$ticketNumber'
    | '/tickets/settings'
    | '/calendar'
    | '/contacts'
    | '/dashboards'
    | '/deals'
    | '/developments'
    | '/reports'
    | '/settings'
    | '/team'
    | '/technician'
    | '/tickets'
    | '/whats-new'
  id:
    | '__root__'
    | '/'
    | '/technician/$activityId'
    | '/tickets/$ticketNumber'
    | '/tickets/settings'
    | '/calendar/'
    | '/contacts/'
    | '/dashboards/'
    | '/deals/'
    | '/developments/'
    | '/reports/'
    | '/settings/'
    | '/team/'
    | '/technician/'
    | '/tickets/'
    | '/whats-new/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TechnicianActivityIdRoute: typeof TechnicianActivityIdRoute
  TicketsTicketNumberRoute: typeof TicketsTicketNumberRoute
  TicketsSettingsRoute: typeof TicketsSettingsRoute
  CalendarIndexRoute: typeof CalendarIndexRoute
  ContactsIndexRoute: typeof ContactsIndexRoute
  DashboardsIndexRoute: typeof DashboardsIndexRoute
  DealsIndexRoute: typeof DealsIndexRoute
  DevelopmentsIndexRoute: typeof DevelopmentsIndexRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  TeamIndexRoute: typeof TeamIndexRoute
  TechnicianIndexRoute: typeof TechnicianIndexRoute
  TicketsIndexRoute: typeof TicketsIndexRoute
  WhatsNewIndexRoute: typeof WhatsNewIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar/': {
      id: '/calendar/'
      path: '/calendar'
      fullPath: '/calendar/'
      preLoaderRoute: typeof CalendarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts/': {
      id: '/contacts/'
      path: '/contacts'
      fullPath: '/contacts/'
      preLoaderRoute: typeof ContactsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboards/': {
      id: '/dashboards/'
      path: '/dashboards'
      fullPath: '/dashboards/'
      preLoaderRoute: typeof DashboardsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals/': {
      id: '/deals/'
      path: '/deals'
      fullPath: '/deals/'
      preLoaderRoute: typeof DealsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developments/': {
      id: '/developments/'
      path: '/developments'
      fullPath: '/developments/'
      preLoaderRoute: typeof DevelopmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/': {
      id: '/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/': {
      id: '/team/'
      path: '/team'
      fullPath: '/team/'
      preLoaderRoute: typeof TeamIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technician/': {
      id: '/technician/'
      path: '/technician'
      fullPath: '/technician/'
      preLoaderRoute: typeof TechnicianIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technician/$activityId': {
      id: '/technician/$activityId'
      path: '/technician/$activityId'
      fullPath: '/technician/$activityId'
      preLoaderRoute: typeof TechnicianActivityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets/': {
      id: '/tickets/'
      path: '/tickets'
      fullPath: '/tickets/'
      preLoaderRoute: typeof TicketsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets/$ticketNumber': {
      id: '/tickets/$ticketNumber'
      path: '/tickets/$ticketNumber'
      fullPath: '/tickets/$ticketNumber'
      preLoaderRoute: typeof TicketsTicketNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets/settings': {
      id: '/tickets/settings'
      path: '/tickets/settings'
      fullPath: '/tickets/settings'
      preLoaderRoute: typeof TicketsSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whats-new/': {
      id: '/whats-new/'
      path: '/whats-new'
      fullPath: '/whats-new/'
      preLoaderRoute: typeof WhatsNewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TechnicianActivityIdRoute: TechnicianActivityIdRoute,
  TicketsTicketNumberRoute: TicketsTicketNumberRoute,
  TicketsSettingsRoute: TicketsSettingsRoute,
  CalendarIndexRoute: CalendarIndexRoute,
  ContactsIndexRoute: ContactsIndexRoute,
  DashboardsIndexRoute: DashboardsIndexRoute,
  DealsIndexRoute: DealsIndexRoute,
  DevelopmentsIndexRoute: DevelopmentsIndexRoute,
  ReportsIndexRoute: ReportsIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  TeamIndexRoute: TeamIndexRoute,
  TechnicianIndexRoute: TechnicianIndexRoute,
  TicketsIndexRoute: TicketsIndexRoute,
  WhatsNewIndexRoute: WhatsNewIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
